 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Ahmed Aboelfetouh
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = {
						PORTA, PIN0, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTA, PIN1, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTA, PIN2, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTA, PIN3, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTA, PIN4, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTA, PIN5, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTA, PIN6, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTA, PIN7, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTB, PIN0, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTB, PIN1, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTB, PIN2, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTB, PIN3, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTB, PIN4, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTB, PIN5, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTB, PIN6, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTB, PIN7, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTC, PIN4, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTC, PIN5, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTC, PIN6, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTC, PIN7, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTD, PIN0, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTD, PIN1, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTD, PIN2, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTD, PIN3, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTD, PIN4, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTD, PIN5, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTD, PIN6, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTD, PIN7, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTE, PIN0, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTE, PIN1, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTE, PIN2, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTE, PIN3, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTE, PIN4, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTE, PIN5, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTF, PIN0, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PortConf_LED1_PORT_NUM, PortConf_LED1_CHANNEL_NUM, OUTPUT, OFF, DIO, STD_HIGH, DISABLLED, DISABLLED,
						PORTF, PIN2, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PORTF, PIN3, INPUT, OFF, DIO, STD_LOW, DISABLLED, DISABLLED,
						PortConf_SW1_PORT_NUM, PortConf_SW1_CHANNEL_NUM, INPUT, PULL_UP, DIO, STD_LOW, DISABLLED, DISABLLED,
};